### ISSUE TITLE
current time

### ISSUE THREAD

**Issue by doubletaketech** [nathanhoneycutt/jquery.progressTimer#4]
Is there a method to get the current time?  If my timer is 60s, and the user finished in 30s, I want to get the time if they finished before the timer completes.

Thanks,
Don

**Comment by doubletaketech** [comment]
Related to that, is there a method to call to stop the timer?  progressTimer('complete') doesn't actually stop the time when it is called, it just changes the bar style.

**Comment by nathanhoneycutt** [comment]
Hey, sorry for the delay in replying to you.  Neither of those are currently features of the progerssTimer.  The scenario I had when I developed it initially this was to force a user to wait a certain amount of time before initiating another action, but to be aware of how much time was remaining.

If you add either piece of functionality, I'll be happy to look at incorporating the change into progressTimer.

**Comment by doubletaketech** [comment]
Thank you Nathan.  Understand your use case.  Great product!
